### ISSUE TITLE
function pg_catalog.date_add("unknown", integer, timestamp with time zone) does not exist

### ISSUE THREAD

**Issue by ivanblagdan** [fivetran/dbt_linkedin#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When running the [ad reporting package](https://hub.getdbt.com/fivetran/ad_reporting/latest/), I'm running into an error with the Linkedin dep. Here's what I'm seeing.
```
17:53:15.691453 [error] [MainThread]: Database Error in model linkedin__ad_adapter (models/linkedin__ad_adapter.sql)
17:53:15.691886 [error] [MainThread]:   function pg_catalog.date_add("unknown", integer, timestamp with time zone) does not exist
17:53:15.692288 [error] [MainThread]:   HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
17:53:15.692671 [error] [MainThread]:   compiled SQL at target/run/linkedin/models/linkedin__ad_adapter.sql
```

### Expected behavior

Ideally, the Linkedin models and the ad reporting models would successfully complete their run.

### dbt Project configurations

models:
  pinterest:
    enabled: false
    # +schema: pinterest
  pinterest_source:
    enabled: false
    # +schema: pinterest_source
  snapchat_ads:
    enabled: false
    # +schema: snapchat_ads
  snapchat_ads_source:
    enabled: false
    # +schema: snapchat_ads_source
  tiktok_ads:
    enabled: false
    # +schema: tiktok_ads
  tiktok_ads_source:
    enabled: false
    # +schema: tiktok_ads_source
  facebook_ads:
    enabled: false
    # +schema: facebook_ads
  facebook_ads_source:
    enabled: false
    # +schema: facebook_ads_source
  facebook_ads_creative_history:
    enabled: false
    # +schema: facebook_ads
  twitter_ads:
    enabled: false
    # +schema: twitter_ads
  twitter_ads_source:
    enabled: false
    # +schema: twitter_ads_source
  microsoft_ads:
    enabled: false
    # +schema: microsoft_ads
  microsoft_ads_source:
    enabled: false
    # +schema: microsoft_ads_source
  # linkedin:
  #   enabled: false
  #   # +schema: linkedin
  # linkedin_source:
  #   enabled: false
  #   # +schema: linkedin_source
  # google_ads:
  #   enabled: false
  #   # +schema: google_ads
  # google_ads_source:
  #   enabled: false
  #   # +schema: google_ads_source

vars:
  api_source: google_ads
  ad_reporting__pinterest_enabled: False
  ad_reporting__microsoft_ads_enabled: False
  ad_reporting__linkedin_ads_enabled: True
  ad_reporting__google_ads_enabled: True
  ad_reporting__twitter_ads_enabled: False
  ad_reporting__facebook_ads_enabled: False
  ad_reporting__snapchat_ads_enabled: False
  ad_reporting__tiktok_ads_enabled: False
  microsoft_ads_schema: bing
  microsoft_ads_database: fivetran
  linkedin_schema: linkedin_ads
  linkedin_database: fivetran  
  pinterest_schema: pinterest
  pinterest_database: fivetran 
  twitter_ads_schema: twitter
  twitter_ads_database: fivetran  
  facebook_ads_schema: facebook
  facebook_ads_database: fivetran 
  google_ads_schema: adwords
  google_ads_database: fivetran 
  snapchat_schema: snapchat
  snapchat_database: fivetran 
  tiktok_ads_schema: tiktok
  tiktok_ads_database: fivetran

### Package versions

packages:
  - package: fivetran/ad_reporting
    version: [">=0.7.0", "<0.8.0"]

### What database are you using dbt with?

redshift

### dbt Version

$ dbt --version
installed version: 1.0.4
   latest version: 1.0.5

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 1.0.0 - Update available!
  Your version of dbt-redshift is out of date! You can find instructions for upgrading here:
  https://docs.getdbt.com/dbt-cli/install/overview

  - postgres: 1.0.4 - Up to date!
  
  $ brew upgrade dbt-redshift
Warning: dbt-labs/dbt/dbt-redshift 1.0.0_3 already installed

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by ivanblagdan** [comment]
Attaching the debug log of the run:
[dbt.log](https://github.com/fivetran/dbt_linkedin/files/8556923/dbt.log)

**Comment by fivetran-joemarkiewicz** [comment]
That's great to hear!! I will move this PR mentioned above into review.

This PR most likely will not be able to be reviewed until late next week (when our next sprint starts). However, in the meantime, I will not make any changes to the existing branch and you are welcome to leverage the branch version. Feel free to follow this issue or the PR for when it is official merged and released.

Thanks again for raising this issue and your help in identifying the solution 😄
