### ISSUE TITLE
look into why we add a day to the adapter model joins...

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_linkedin#20]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

investigate why we changed it to that...

https://getdbt.slack.com/archives/C01D1R2JLLA/p1650539408651009

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-jamie** [comment]
So this will actually become a non-issue soon. in every other ad reporting package, we only join in the **latest version** of entities like accounts or campaigns or creatives. We will be extending this to linkedin as well, as it currently joins in the historical version of the entity that was valid at the time. 

So, [these](https://github.com/fivetran/dbt_linkedin/blob/main/models/linkedin__ad_adapter.sql#L54-L70) lines
```sql
 from metrics
    left join creatives
        on metrics.creative_id = creatives.creative_id
        and {{ fivetran_utils.timestamp_add('day', 1, 'metrics.date_day') }} >= creatives.valid_from
        and {{ fivetran_utils.timestamp_add('day', 1, 'metrics.date_day') }} <= coalesce(creatives.valid_to, {{ fivetran_utils.timestamp_add('day', 1, dbt_utils.current_timestamp()) }})
```

will instead look like
```sql
 from metrics
    left join creatives
        on metrics.creative_id = creatives.creative_id
        and creatives.is_lastest_version = true
```

We'll be rolling this out in the next month or so as part of our big Ad Reporting V2 updates.

As for the original question though (why are we adding a day) I believe this is because the `valid_to` and `valid_from` fields are timestamps that could be in the middle of a `date_day`, which starts at 00:00. an alternative solution would've been to `date_trunc` the `valid_from` and `valid_to` fields and then compare them (without adding a day)

**Comment by fivetran-joemarkiewicz** [comment]
The latest version of the Ad Reporting package (`v.1.0.0`) does not use this logic anymore. As such, we can comfortably close this issue as it is no longer relevant.
