### ISSUE TITLE
[Bug] is_latest_version filter omitted from url report

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_linkedin#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Currently the [linkedin_ads__url_report](https://github.com/fivetran/dbt_linkedin/blob/main/models/linkedin_ads__url_report.sql) could possible be brining in multiple records due to the omission of the `is_latest_version` filter within the [creative cte](https://github.com/fivetran/dbt_linkedin/blob/5adac0892054c07986aa5ce6679acbeb1bfbe9df/models/linkedin_ads__url_report.sql#L3-L7).

We can see that this filter is properly applied to our [other end models](https://github.com/fivetran/dbt_linkedin/blob/5adac0892054c07986aa5ce6679acbeb1bfbe9df/models/linkedin_ads__creative_report.sql#L3-L8) and should be applied to the URL report as well. This will ensure we are not duplicating the end model records and only bringing in the latest records.

### Relevant error log or model output

```shell
Multiple records could end up in the end models.
```

### Expected behavior

The end model only returns the latest versions of the ads.

### dbt Project configurations

N/A

### Package versions

v1.1.0

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery, databricks

### dbt Version

v1.3.1

### Additional Context

See the [dbt Slack convo](https://getdbt.slack.com/archives/CU4MRJ7QB/p1672933483736549) for more details

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by epapineau** [comment]
We're working on upgrading our dbt packages and are experiencing a failure on the `dbt_utils_unique_combination_of_columns_linkedin_ads__url_report_date_day__creative_id__campaign_id__campaign_group_id__account_id` test. Is that likely due to this issue?

**Comment by fivetran-joemarkiewicz** [comment]
Hey @epapineau I would agree that this is likely causing the test failure you are experiencing. 

The user who initially raised this issue in dbt Slack mentioned they would be open to contribute to address this issue. If there is no movement by the start of next week we can pick this up and push the update to the next patch release.

**Comment by epapineau** [comment]
Thanks for the update @fivetran-joemarkiewicz! Super helpful context for us.

**Comment by fivetran-joemarkiewicz** [comment]
The PR mentioned above has been merged and released in v0.6.1! This should resolve the original issue and will be live on the dbt hub at the top of the hour. As such, I will close out this issue. 

Please feel free to re-open the issue if the problem continues to persist after the upgrade is live at the top of the hour.
