### ISSUE TITLE
[Feature] LinkedIn API Changes

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_linkedin#27]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The LinkedIn API has changed and a rollout of these changes within the Fivetran connector will impact the schema which this package is currently using. This will result in a breaking change and need to be updated to ensure LinkedIn users are getting the most up to date and accurate data from their Fivetran LinkedIn connector.

### Describe alternatives you've considered

Please see internal notes for more details on what updates will most likely need to be rolled out. This is still in a discovery phase and more details will be shared as we learn more.

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

We will need to understand if these API changes are being rolled out to all Fivetran LinkedIn customers or just a few periodically, this will impact our approach to resolving the API differences within this package and the source.

This update _should_ also address Issue #5

**Comment by brendangeisler** [comment]
Hello - Just reporting that today I'm receiving an error that the linkedin_ads__creative_report is failing on the creative_id not null tests.  Hoping that it's addressed with this issue.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @brendangeisler thanks for chiming in here! We actually have a working PR that may address the issue you are experiencing (see the PR #28 for more details). If you are able, it would be incredibly helpful if you would be able to test the branch on your data to see if it addresses the API changes. You can test this branch using the below package version in your packages.yml
```yml
packages:
  - git: https://github.com/fivetran/dbt_linkedin.git
    revision: feature/linkedin-api-updates-2023
    warn-unpinned: false
```
