### ISSUE TITLE
dbt_utils dependency conflict with fivetran/dbt_fivetran_log

### ISSUE THREAD

**Issue by javidigani** [fivetran/dbt_linkedin#3]
When attempting to build both the dbt_linkedin and dbt_fivetran_log packages in the same project, a dependency error arises on the dbt_utils package. dbt_linkedin references dbt_utils 0.5.0, whereas dbt_fivetran_log references 0.5.1. 

It's worth noting that these packages build successfully independent of each other.

One workaround is to fork the dbt_linkedin project, update dbt_utils to 0.5.1 and reference the forked git repo in your packages.yml file. @DylanBaker mentioned the possibility of being less strict on package versions, though this requires testing.

**Comment by jmak123** [comment]
Same issue here, the Fivetran packages are quite useful, would be great if they can live in the same local project.

**Comment by fivetran-jamie** [comment]
hey there -- thanks for surfacing this, and sorry for the wait! we've recently updated all of our packages to require the same dbt_utils version (`[>=0.6.0, <0.7.0]`)

re-installing the packages should eradicate any conflicts, though FYI these new releases do require >= dbt 0.18.0!
- [fivetran_log](https://hub.getdbt.com/fivetran/fivetran_log/latest/)
- [linkedin](https://hub.getdbt.com/fivetran/linkedin/latest/)
