### ISSUE TITLE
[Bug] Avoid duplicate column errors for users already including `conversion_value_in_local_currency` as a passthrough field

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_linkedin#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The recent conversions release is intended to be backwards compatible and not cause any errors for folks who have already been including conversions via our existing passthrough column framework. For the most this was achieved, but we missed the case of `conversion_value_in_local_currency`.

### Relevant error log or model output

```shell
Database Error in model linkedin_ads__account_report (models/linkedin_ads__account_report.sql)
  CREATE TABLE has columns with duplicate name conversion_value_in_local_currency at [15:1]
  compiled code at target/run/linkedin/models/linkedin_ads__account_report.sql
```

### Expected behavior

Should run without error. `conversion_value_in_local_currency` is included in my model 

### Possible solution

Adapt solution from [Snapchat ads](https://github.com/fivetran/dbt_snapchat_ads/pull/28)

### dbt Project configurations

```yml
vars:
  linkedin_ads__campaign_passthrough_metrics:
    - name: 'conversion_value_in_local_currency'
```

### Package versions

v0.9.0

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery, databricks

### How are you running this dbt package?

dbt Core™

### dbt Version

Core:
  - installed: 1.8.7
  - latest:    1.8.8 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.8.7 - Up to date!
  - bigquery:   1.8.3 - Up to date!
  - snowflake:  1.8.4 - Up to date!
  - redshift:   1.8.1 - Up to date!
  - postgres:   1.8.2 - Up to date!
  - spark:      1.8.0 - Up to date!

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as it's been addressed in the latest release.
